name: Upload Python Package
on:
  release:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/ansi-string
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1